github.com:
    users:
        zinat-kwakye:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: zinat-kwakye
