apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer # set the type of Service
  selector:
    app: frontend # referencing the Pod's label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
---
# Pod config below