apiVersion: v1
kind: Service
metadata:
  name: flaskapp
spec: 
  type: LoadBalancer
  selector:
    app: flaskapp
  ports:
  - name: http
    protocol: TCP
    port: 80         #this exposes the service to external traffic.
    targetPorts: 5500           #this is the container/pod port.
  