apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers: 
  - name: mysql
    image: mysql:latest
    env: 
      - name: MYSQL_DATABASE
        value: mydatabase
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: mysql_password
    ports:
    - containerPort: 3306

